version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: unassigned_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - target: 9000
      - published: 9000
    command: --init-file /data/application/init.sql
    volumes:
      - mysql_db_data_container:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - app_network
    restart: unless-stopped
  backend:
    depends_on:
      - mysql
    build:
      context: ./backend
      container_name: unassigned_api_dev
    ports:
      - target: 9000
      - published: 9000
    env_file: ./backend/.env
    volumes: ./backend:/app
    networks:
      - app_network
networks:
  - app_network
volumes:
  mysql_db_data_container: